### ISSUE TITLE
With the new user layout the table is not completed

### ISSUE THREAD

**Issue by tfoote** [ASKBOT/askbot-devel#165]
It used to be 4x7 netting 28 per page, but now it's 5x6 

But the number of entries is still limited to 28 leaving 2 empty slots in the bottom row. 

I think this is the config parameter which needs to update: 

https://github.com/ASKBOT/askbot-devel/blob/d221c840fc25b06c4dc0ebe50b94a1d93e1442ad/askbot/const/__init__.py#L358

**Comment by evgenyfadeev** [comment]
Fixed in b908afb9ee50d937ad242a2908dca8e2556b7502
