### ISSUE TITLE
I suggest to fix all askbot requirements lib versions

### ISSUE THREAD

**Issue by harobed** [ASKBOT/askbot-devel#178]
Hi,

I suggest you to fix all your library version in https://github.com/ASKBOT/askbot-devel/blob/master/askbot_requirements.txt

Example, now I use Django 1.3.7 and django-robots==0.9.2 isn't compatible with this Django version : 

https://gist.github.com/harobed/e35f3bd9219ecb283e21

What do you think about this suggestion ?

Best regards,
Stephane

**Comment by evgenyfadeev** [comment]
Stephane, I think that fixing all would be overly restrictive as it may make Askbot incompatible with other apps requiring their own fixed versions. Currently most dependencies are version-limited from above.

Maybe adding a sample requirements file that is guaranteed to work would be good, but that would be a different issue, so closing this.
