### ISSUE TITLE
duplicate text on closed questions

### ISSUE THREAD

**Issue by nilesjohnson** [ASKBOT/askbot-devel#289]
The explanation of a closed question has duplicate text.  E.g., the text on a recently closed question at ask.sagemath.org is:

_Closed for the following reason spam or advertising by Closed for the following reason "spam or advertising" by calc314 
close date 2014-07-22 07:34:40.192207_

**Comment by ozbek** [comment]
This appears to be fixed, please consider closing.

**Comment by slel** [comment]
The two examples mentioned above seem fixed indeed.

**Comment by ozbek** [comment]
d1cae4076a8d83c0b7cdfe53a22688ddc4c5ad46

**Comment by evgenyfadeev** [comment]
Thanks @ozbek.
