### ISSUE TITLE
Latest master allows case-variant tags

### ISSUE THREAD

**Issue by geekofalltrades** [ASKBOT/askbot-devel#312]
I've got the latest master checked out, with the sqlite3 backend (for convenience), using runserver in debug mode.  I'm able to ask a question and create tags that are case-variants.  Currently I have one question tagged with both 'excitement' and 'EXCITEMENT', and another tagged with both 'tag' and 'TAG'.

**Comment by evgenyfadeev** [comment]
it's been fixed.
