### ISSUE TITLE
Activity.receiving_users

### ISSUE THREAD

**Issue by geekofalltrades** [ASKBOT/askbot-devel#327]
There is a ManyToManyField on Activity to User called `receiving_users`.  It is completely unused.  A search for it in the code base outside of the migrations yields no results.  Its related_name, `received_activity`, also yields no results.

Activity also has a ManyToManyField to User called `recipients`, which has presumably taken its place.

Unless `receiving_users` has a function I'm not aware of, it should be removed.

**Comment by evgenyfadeev** [comment]
Thank you. Forgot to remove the relation quite a while ago!
