### ISSUE TITLE
Can't navigate to other pages in 'followed questions' / 'favorites' profile section

### ISSUE THREAD

**Issue by gavanderhoorn** [ASKBOT/askbot-devel#333]
After opening the *Followed Questions* page of a user's profile (ie: `http://answers.domain.tld/users/1234/username/?sort=favorites`), the pagination links at the bottom of the page (the links with the page numbers: 1, 2, 3, 4, ..) seem to do nothing.

The URL is `http://answers.domain.tld/users/1234/username/?page=N` (with `N` the page number), but clicking on it does not take the user to a new page, or update the current page with other followed questions.

(this is on the ROS Answers askbot instance).

**Comment by evgenyfadeev** [comment]
fixed in the master branch, need to update your instance.
