### ISSUE TITLE
Unusual karma activity

### ISSUE THREAD

**Issue by dfarrell07** [ASKBOT/askbot-devel#336]
[This karma activity](https://ask.opendaylight.org/users/11/lori/?sort=reputation) seems like it shouldn't be possible.

Basically, there's a question posted by an anonymous user that a signed-in user answered. The anon user accepted the answer (+15 karma) and then apparently -1'd it (-5 karma). That cycle repeated, allowing a total of +10 karma for every cycle.

I tried to replicate it by asking a question anonymously (but while logged into my account), answering the question and then accepting my own answer, but didn't get the +15, -5 cycle shown there. Maybe two accounts are needed?

Looks like a bug, but I'm hesitant to create a second account to continue attempting to replicate it (seems ethically dubious). Thoughts?

**Comment by evgenyfadeev** [comment]
Thank you, fixed in 44eb4a006902c369492e95edda6b162cc4fbc81b. There were actually several possibilities for the reputation gaming as there were separate settings for rep change on canceling some actions in addition to rep changes on "forward" actions.
