### ISSUE TITLE
askbot-setup does not correctly set the database name using the CLI switches

### ISSUE THREAD

**Issue by xupit3r** [ASKBOT/askbot-devel#351]
Supplying `askbot-setup` with the `-d` switch (for the database name) does not properly set the database name in `settings.py` (instead, the database name is set to `omain`). Other switches (as specified by the documentation here: http://askbot.org/doc/initial-configuration.html) appear to be working correctly.

**Comment by evgenyfadeev** [comment]
Sorry for the wait to get to the issue. I was unable to reproduce, tried many different ways.
Closing this, please reopen if you could give exact command to reproduce.
