### ISSUE TITLE
Error while installing askbot

### ISSUE THREAD

**Issue by abhishek6590** [ASKBOT/askbot-devel#396]
HI,

I am facing the following error while installing askbot through virualenv using git repository - python setup.py develop
  File "setup.py", line 129
    **************************************************************"""
                                                                    ^
SyntaxError: invalid syntax

Please suggest me what can I do ?

Thanks

**Comment by evgenyfadeev** [comment]
Are you using python3?

On Thu, Feb 12, 2015 at 6:36 PM, abhishek6590 <notifications@github.com>
wrote:

> HI,
>
> I am facing the following error while installing askbot through virualenv
> using git repository - python setup.py develop
> File "setup.py", line 129
> **************************************************************"""
> ^
> SyntaxError: invalid syntax
>
> Please suggest me what can I do ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/396>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by abhishek6590** [comment]
Hi,

Yes I am using python3.

**Comment by evgenyfadeev** [comment]
Not compatible with python 3.

On Thu, Feb 12, 2015 at 7:32 PM, abhishek6590 <notifications@github.com>
wrote:

> Hi,
>
> Yes I am using python3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/396#issuecomment-74167923>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by abhishek6590** [comment]
OK . So which version should I use for this ?

**Comment by abhishek6590** [comment]
I tried with but still the same issue

**Comment by evgenyfadeev** [comment]
could you please give steps to reproduce this issue, assuming that
I don't have any custom python module installed?

On Thu, Feb 12, 2015 at 8:38 PM, abhishek6590 <notifications@github.com>
wrote:

> I tried with but still the same issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/396#issuecomment-74177243>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by FedericoCeratto** [comment]
Supported versions: https://github.com/ASKBOT/askbot-devel/blob/master/setup.py#L43
