### ISSUE TITLE
check if user can reopen question on POST request

### ISSUE THREAD

**Issue by czpython** [ASKBOT/askbot-devel#397]
@evgenyfadeev  we should move [this](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/views/commands.py#L845) to [above the if](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/views/commands.py#L841)

the reason being we should check if user can reopen a question regardless of the request method.

**Comment by evgenyfadeev** [comment]
the assertion is called from within user.reopen_question()
