### ISSUE TITLE
check if user can close question on POST request

### ISSUE THREAD

**Issue by czpython** [ASKBOT/askbot-devel#398]
same as #397 we should move the[assert](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/views/commands.py#L818) to happen if request is POST as well.

**Comment by evgenyfadeev** [comment]
there is an assertion that is called from within "user.close_question()".
As a rule, those exceptions are called in the beginning of the user action method.

https://github.com/ASKBOT/askbot-devel/commit/c41e5436b624bbfb30a964dcecf2fde176d88393
