### ISSUE TITLE
verify user is moderator when merging questions

### ISSUE THREAD

**Issue by czpython** [ASKBOT/askbot-devel#399]
in the [merge question view](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/views/commands.py#L1482) we say this is only allowed for moderators and yet only check if the user is logged in which means **any** user can run this operation, we should check if the user is indeed a moderator.

**Comment by evgenyfadeev** [comment]
https://github.com/ASKBOT/askbot-devel/commit/8adf52c3fe12b29573f58cb11ade94b479164b75

this base assertion is called when merge is attempted.
