### ISSUE TITLE
check if user is readonly when commenting on answer

### ISSUE THREAD

**Issue by czpython** [ASKBOT/askbot-devel#400]
we need to call ```user.is_read_only()``` [here](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/views/writers.py#L903)

**Comment by evgenyfadeev** [comment]
yes, that's right.

**Comment by evgenyfadeev** [comment]
https://github.com/ASKBOT/askbot-devel/commit/8adf52c3fe12b29573f58cb11ade94b479164b75
