### ISSUE TITLE
blocked/readonly user should not be allowed to join group

### ISSUE THREAD

**Issue by czpython** [ASKBOT/askbot-devel#401]
in [get_openness_level_for_user](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/models/user.py#L621) there's no check for users blocked/suspended or readonly status.

**Comment by evgenyfadeev** [comment]
https://github.com/ASKBOT/askbot-devel/commit/ef5e698be8ae535d6ade2abe67d5be5e31f42c41
