### ISSUE TITLE
mark-tags should check if user is allowed to subscribe/unsubscribe to a tag

### ISSUE THREAD

**Issue by czpython** [ASKBOT/askbot-devel#403]
currently the code in [user_mark_tags](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/models/__init__.py#L1383) never checks if the user is readonly or even blocked/suspended.

I'm not sure how this mechanism works, but if we display the tags for the user to subscribe then it might be tricky since we would then have to hide it for this types of user.

**Comment by evgenyfadeev** [comment]
https://github.com/ASKBOT/askbot-devel/commit/566decd96a636130cd83f4a6b5398dc46eb3630b
