### ISSUE TITLE
save_draft_answer should check user permissions

### ISSUE THREAD

**Issue by czpython** [ASKBOT/askbot-devel#404]
[save_draft_answer](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/views/commands.py#L1248) should look at blocked/suspended/readonly and also the global readonly setting

**Comment by evgenyfadeev** [comment]
https://github.com/ASKBOT/askbot-devel/commit/7d1f4b7f1e1d8822e12b5ae112c885ff4507e7af
