### ISSUE TITLE
toggle_follow_question needs to check permissions

### ISSUE THREAD

**Issue by czpython** [ASKBOT/askbot-devel#405]
[toggle_follow_question](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/views/commands.py#L714) should not allow blocked/suspended, readonly? users to follow question.

**Comment by evgenyfadeev** [comment]
https://github.com/ASKBOT/askbot-devel/commit/cb0454d8d75d42f550d06a005f3b7fb90408ae50
