### ISSUE TITLE
Is the Chinese team on transifex still active?

### ISSUE THREAD

**Issue by zheli** [ASKBOT/askbot-devel#416]
I requested to become the Chinese translator long time ago but didn't get any response. And I can only improve translations in my own fork. Are the members still active there?

**Comment by evgenyfadeev** [comment]
Hello, I've looked through pending join requests and approved them. Are you able to translate now at the transifex?

**Comment by zheli** [comment]
Hi Evegny! Can you check it again and approve my request?

**Comment by zheli** [comment]
@evgenyfadeev hi! can you check it again and approve my request?

**Comment by evgenyfadeev** [comment]
Hi, sorry just approved you.

Best regards,
Evgeny.

On Sun, Mar 22, 2015 at 11:50 AM, Zhe Li <notifications@github.com> wrote:

> @evgenyfadeev <https://github.com/evgenyfadeev> hi! can you check it
> again and approve my request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/416#issuecomment-84625062>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by zheli** [comment]
thx @evgenyfadeev !
