### ISSUE TITLE
Error registering the first user

### ISSUE THREAD

**Issue by manelvf** [ASKBOT/askbot-devel#432]
After installing the development version, and going through all the steps, when accessing /account/register, after filling the form I get:

'openid_url' cannot be null

when set to not null on the database, it also complains about other fields in the same table. After setting all to not null, then complains about a missing table that is not on the scheme.

**Comment by manelvf** [comment]
Steps to reproduce it:
- git clone askbot-devel master branch
- askbot-setup
- python setup.py develop
- I create the database in mysql.
- askbot-setup
- python manage.py collectstatic
- python manage.py syncdb
- python manage.py migrate askbot
- python manage.py migrate django_authopenid
- Then I open the browser with the index page. It's OK
- I try to create the first user, go to /account/register
- Filling the form with username and email
- Redirects to Error 500, 'openid_url' cannot be null


Using Python 2.7.9, in Debian Wheezy. I think I've followed the correct
steps for checking it. It seems that it tries to register using OpenID, but
not provider has been found. Maybe I should setup a provider.



2015-04-05 19:05 GMT+02:00 Evgeny Fadeev <notifications@github.com>:

> Could you describe pls the steps or point me to a description you are
> following and tell at which step there is this error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/432#issuecomment-89812813>.
>



-- 
Manel Villar
Paulsborner Str. 9
10709 Charlottenburg
Berlin (Deutschland)

Tel: (+49) (0)162 6574604
skype: manel.villar
manelvf@gmail.com

*"Ars longa, vita brevis"*

**Comment by evgenyfadeev** [comment]
This url is not to be used directly, without extra parameters. Added redirect when url to the signin page in commit e2ac28c9d1c845df534b0d49acb5c5a2103e5855.

If you follow links in the UI registration works and with the redirect above takes care of the reported issue.
