### ISSUE TITLE
'edit' & 'convert to answer' links disappear for non-admin-comment-authors upon 'add a comment'/'show more comments'

### ISSUE THREAD

**Issue by knowledgepoint-devs** [ASKBOT/askbot-devel#437]
Noticed in Knowledgepoint instance (\*) using [current head of merge1 branch of askbot](https://github.com/ASKBOT/askbot-devel/commit/fbe5702c4e276dac5895f1916b5f05e1d693f64c).

However, I'm confident this will also be affecting other instances using askbot merge1 branch.

To reproduce:

* log in as a non-admin user and view a question
* add a comment - you'll see the new comment with an 'edit' link
* now refresh the page and you'll see that you not only have an 'edit' link for your comment, but also a 'convert to answer' link - but we should have seen that as soon as the comment was first rendered (via javascript)

Repeat for an admin user and this works fine - as soon as the comment is rendered (when user has just created it), it has both links showing. 

Immediately following comment creation, the link is created by [post.js at L2458](https://github.com/ASKBOT/askbot-devel/blob/9174782b49ea35618d01f5861f9ab188d4ebf353/askbot/media/js/post.js#L2458) if this.\_is\_convertible (_ie. [if the current user is an admin or mod user](https://github.com/ASKBOT/askbot-devel/blob/9174782b49ea35618d01f5861f9ab188d4ebf353/askbot/media/js/post.js#L2227)_). Upon page load on the other hand, the link is created by [macros.html](https://github.com/ASKBOT/askbot-devel/blob/79b7ef1bac75a3a95d514becfe24e8b60dccb64b/askbot/templates/macros.html#L431) and is hidden via javascript in [question.html](https://github.com/ASKBOT/askbot-devel/blob/merge1/askbot/templates/question.html#L304) _unless the user is an admin/mod OR the user is the author_. In conclusion, the logic differs in both situations. The logic in post.js should instead create the link if the current user is an admin/mod user OR is the comment author and then it will match the logic in question.html's inline javascript.

\* with a small css tweak to stop hiding 'convert to answer' links

**Comment by evgenyfadeev** [comment]
fixed in the master branch

**Comment by jogwen** [comment]
We've since decided in KP we won't want to show this to comment authors anyway (only to admin/mods), so we don't need the fix for KP at the moment. Glad there's a fix in the pipeline for merge1 branch though - we might change our minds one day!
