### ISSUE TITLE
question search text error on postgres

### ISSUE THREAD

**Issue by kyleboyle** [ASKBOT/askbot-devel#438]
The query generated by models.tag.get_related_to_search generates an error on postgres:

```
invalid reference to FROM-clause entry for table "askbot_thread"
LINE 1: ...d" = false  AND U1."post_type" = 'question'  AND (askbot_thr...
```

The query: 
```
SELECT "tag"."id",
 "tag"."name",
 "tag"."created_by_id",
 "tag"."language_code",
 "tag"."status",
 "tag"."used_count",
 "tag"."deleted",
 "tag"
."deleted_at",
 "tag"."deleted_by_id",
 "tag"."tag_wiki_id",
 COUNT("tag"."id") AS "local_used_count" FROM "tag" INNER JOIN "askbot_thread_tags" ON ("tag"."id" = "askbot_thread_tags"."tag_id") WHERE ("askbot_thread_tags"."thread_id" 
    IN (SELECT DISTINCT U0."id" FROM "askbot_thread" U0 INNER JOIN "askbot_post" U1 ON (U0."id" = U1."thread_id") WHERE (U1."deleted" = False  AND U1."post_type" = question 
        AND (askbot_thread.text_search_vector @@ plainto_tsquery(english, ch)))) AND NOT ("tag"."deleted" = True )) GROUP BY "tag"."id",
 "tag"."name",
 "tag"."created_by_id",
 "tag"."language_code",
 "tag"."status",
 "tag"."used_count",
 "tag"."deleted",
 "tag"."deleted_at",
 "tag"."deleted_by_id",
 "tag"."tag_wiki_id" ORDER BY "local_used_count" DESC,
 "tag"."name" ASC
```

This seems to be an issue with some full text search lib not knowing how to deal with column aliases.

changing ```...self.filter(threads__in=threads)....``` to ```...self.filter(threads__in=list(threads))....``` will fix the issue, but not as efficient.

**Comment by zheli** [comment]
I have this issue as well, should we do list() on qs?

https://github.com/ASKBOT/askbot-devel/commit/0e7ba659a627303e35e4e1d4309fd2dc33ba8ae0#diff-f2790a1164a1d006f9d08be6d0832248

**Comment by kyleboyle** [comment]
Maybe, or maybe there is a fix to whatever lib is generating the postgres query. Good find thanks for finding the change

**Comment by evgenyfadeev** [comment]
Thank you, I've reverted the referenced commit. Please close if this fixes the issue for you.
