### ISSUE TITLE
Sort users other than by karma is broken

### ISSUE THREAD

**Issue by slel** [ASKBOT/askbot-devel#457]
In Askbot 0.7.53, sorting users other than by karma is broken:
all other sortings fail to apply.

For example, at ask-sage, where the 'users' page

  http://ask.sagemath.org/users/

lists users with the default sorting (by karma),
the buttons 'recent', 'oldest', 'by username' link to

  http://ask.sagemath.org/users/?sort=newest
  http://ask.sagemath.org/users/?sort=last
  http://ask.sagemath.org/users/?sort=user

where the requested sorting is not applied.

Only the karma sorting (coinciding with the default) works,
with the 'karma' button linking to

  http://ask.sagemath.org/users/?sort=reputation

Note that http://askbot.org/en/, currently using Askbot 0.7.48,
does not have that problem, see

  http://askbot.org/en/users/

where buttons 'karma', 'recent', 'oldest', 'by username'  all work.

**Comment by zheli** [comment]
+1

**Comment by nARN** [comment]
JFYI, I've forked 40a1eca38d4bf9f6fae53e1d65a9551f0f69454c and do not have this problem. Didn't investigate thoroughly but likely it's been fixed by 95febca4

**Comment by evgenyfadeev** [comment]
Sorting bugs were fixed, thank you.
