### ISSUE TITLE
FieldError at /

### ISSUE THREAD

**Issue by Sshuichi** [ASKBOT/askbot-devel#463]
Hello.

After installing (following the docs), and running ther server I've got the following error

    FieldError at /
    Unknown field(s) (a, l, _) specified for Rule

Can you help me with it ?

**Comment by KurtPfeifle** [comment]
See here:

* http://askbot.org/en/question/13218/fielderror-at/

Circumvent it by running

    pip install django-robots==1.0

**Comment by evgenyfadeev** [comment]
added fixed version requirement for django-robots
