### ISSUE TITLE
DatabaseError at /questions/

### ISSUE THREAD

**Issue by laike9m** [ASKBOT/askbot-devel#478]
I'm using he latest version 0.7.53. Visit homepage or any other page gives me such error:

```
DatabaseError at /questions/
relation "group_messaging_unreadinboxcounter" does not exist
LINE 1: ..."group_messaging_unreadinboxcounter"."count" FROM "group_mes...
                                                             ^
Request Method:	GET
Request URL:	http://127.0.0.1:8000/questions/
Django Version:	1.5.12
Exception Type:	DatabaseError
Exception Value:	
relation "group_messaging_unreadinboxcounter" does not exist
LINE 1: ..."group_messaging_unreadinboxcounter"."count" FROM "group_mes...
                                                             ^
Exception Location:	/Users/laike9m/Dev/Python/Envs/fbtask/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py in execute, line 54
Python Executable:	/Users/laike9m/Dev/Python/Envs/fbtask/bin/python
Python Version:	2.7.6
```

**Comment by evgenyfadeev** [comment]
Just type "python manage.py syncdb --migrate" this will build all the
database tables.

On Fri, Jun 19, 2015 at 8:30 AM, Yao Zuo <notifications@github.com> wrote:

> I'm using he latest version 0.7.53. Visit homepage or any other page gives
> me such error:
>
> DatabaseError at /questions/
> relation "group_messaging_unreadinboxcounter" does not exist
> LINE 1: ..."group_messaging_unreadinboxcounter"."count" FROM "group_mes...
>                                                              ^
> Request Method: GET
> Request URL:    http://127.0.0.1:8000/questions/
> Django Version: 1.5.12
> Exception Type: DatabaseError
> Exception Value:
> relation "group_messaging_unreadinboxcounter" does not exist
> LINE 1: ..."group_messaging_unreadinboxcounter"."count" FROM "group_mes...
>                                                              ^
> Exception Location: /Users/laike9m/Dev/Python/Envs/fbtask/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py in execute, line 54
> Python Executable:  /Users/laike9m/Dev/Python/Envs/fbtask/bin/python
> Python Version: 2.7.6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/478>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by laike9m** [comment]
The odd thing is, I've done it, and it did work, then suddenly every page gave me that error.
