### ISSUE TITLE
UndefinedError at /account/signin/  ...LoginForm object' has no attribute 'possword'

### ISSUE THREAD

**Issue by pgil80** [ASKBOT/askbot-devel#479]
Hi !

I've just installed AskBot from sources (directly from the master of askbot-devel) for evaluation purpose.
The user creation process works correctly (I think...) but when I try to sign in, the following exception is raised : 

UndefinedError at /account/signin/
'askbot.deps.django_authopenid.forms.LoginForm object' has no attribute 'possword'
Request Method:	POST
Request URL:	http://mydomain:8888/account/signin/
Django Version:	1.5.12
Exception Type:	UndefinedError
Exception Value:	
'askbot.deps.django_authopenid.forms.LoginForm object' has no attribute 'possword'
Exception Location:	C:\Python27\lib\site-packages\jinja2\environment.py in getattr, line 397
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.10

Any help will be appreciate !

**Comment by nARN** [comment]
I believe this have been already fixed by 9325371d64c12d95ada80171cc399d01a17313e9

**Comment by evgenyfadeev** [comment]
Sorting bugs were fixed, thanks.
