### ISSUE TITLE
askbot-setup does not ask for database-name when using mysql

### ISSUE THREAD

**Issue by KonstantinSchubert** [ASKBOT/askbot-devel#480]
For some reason askbot-setup does not ask for the dbase name when choosing mysql, leading to an empty string in settings.py.

I haven't tested it, but I assume it is because this line here https://github.com/ASKBOT/askbot-devel/blob/master/askbot/deployment/__init__.py#L205

always evaluates to true. The default value of `'database_name'` in `options_dict` is None. That means that the key exists, just the value is None. Thus the expression `'database_name' in options_dict`evaluates true, even if `database_name  is None`.

**Comment by evgenyfadeev** [comment]
Thank you, 8d786edfe4c3eb00759b6a33b61506119c289aa9 fixes this issue.
