### ISSUE TITLE
replace gravatar with libravatar?

### ISSUE THREAD

**Issue by Matthias84** [ASKBOT/askbot-devel#481]
Hi,

gravatar is an comfortable service to link an avatar logo to your mailaccount without using social logins etc. Unfortunatly this causes some privacy problems, as www.gravatar.com can log such lookups and thus track people, create contact graphs etc...

Therefore www.libravatar.org can be used as an selfhosting alternative. It's open source and several libs for python and django exist to replace gravatar without a lot of work. As a fallback they can also use gravatar to simplify migration.

It would be nice, if askbot could try to implement this, too :-)

**Comment by evgenyfadeev** [comment]
There is an option for custom hosting of gravatars - please have a look in the "settings" -> "user settings"
