### ISSUE TITLE
Why didn't the signup request handled by signup_with_password view?

### ISSUE THREAD

**Issue by laike9m** [ASKBOT/askbot-devel#484]
I have two webapps, one is askbot. I was trying to use CORS to sign up askbot from another webapp. I use [django-cors-headers][1] lib to add CORS headers to askbot response, so askbot didn't raise 403 error. 

Here's the response
![2015-06-27 4 53 57](https://cloud.githubusercontent.com/assets/2592205/8391245/1dbc242e-1cee-11e5-997d-ca759926ee52.png)

But signup failed, nothing was written into DB. So I add a print statement in [signup_with_password][2]. Suprisingly, nothing got printed, response didn't enter this view function.

Any help is appreciated.

[1]: https://github.com/ottoyiu/django-cors-headers
[2]: https://github.com/ASKBOT/askbot-devel/blob/master/askbot/deps/django_authopenid/views.py#L1236

**Comment by evgenyfadeev** [comment]
please see if CSRF protect middleware rejected the post request.

**Comment by evgenyfadeev** [comment]
Response was 302 redirect. Where did it redirect?

**Comment by laike9m** [comment]
I don't know for sure, but it works now. Thx evgenyfadeev.
