### ISSUE TITLE
add support for django 1.8+ and drop support of remaining ones.

### ISSUE THREAD

**Issue by auvipy** [ASKBOT/askbot-devel#485]
drop support anything less then 1.7

**Comment by evgenyfadeev** [comment]
Django 1.7 is supported in the master branch and releases of 0.9 series.

**Comment by evgenyfadeev** [comment]
branch dj-18 supports django 1.8. In the future refer to the documentation for the django version support. Hopefully versions of series 0.9.x will be supporting 1.8 but it may require a separate subversion, not decided yet.
