### ISSUE TITLE
formatting of mobile version

### ISSUE THREAD

**Issue by oberon2007** [ASKBOT/askbot-devel#495]
On the small screen of my Samsung Galaxy S3-mini the buttons 'comment', 'edit', 'flag... of the askbot site http://faq.i3wm.org are overlapping and not usable. Also 'sign out' is cut off and 'help' not present at all - it is probably outside the screen... Using the page in landscape mode is not really better and the buttons are still not usable like mentioned above.

**Comment by evgenyfadeev** [comment]
https://github.com/ASKBOT/askbot-devel/commit/8373ec235e405d0d81373755da27d6a762e28d3b addresses the issue.
