### ISSUE TITLE
noCAPTCHA support

### ISSUE THREAD

**Issue by wirehell** [ASKBOT/askbot-devel#514]
We are being hit by a spamming botnet. reCAPTCHA prevents most new user creation but a significant number of spam users are still created. I would like to try the noCAPTCHA option, but this is not supported in django-recaptcha-works (which seems to be a dead project since 2010). 
Django-recaptcha (https://github.com/praekelt/django-recaptcha) supports noCAPTCHA and seems like a good replacement.

**Comment by Airblader** [comment]
+1, we are also seeing spam and it seems to be hard to defend against it.

**Comment by evgenyfadeev** [comment]
nocaptcha is supported in 0.7.54 for django 1.5 and 1.6 and 0.9.0 for django 1.7
