### ISSUE TITLE
follow button: username overlaps number of questions

### ISSUE THREAD

**Issue by slel** [ASKBOT/askbot-devel#518]
On the profile page for a user, there is a follow button that reads "follow xyz" but apart from very short usernames, typically the username is on a second line and overlaps the number of questions asked by that user.

See the screenshot from http://askbot.org/en/users/148/kcrisman/

![scr_2015-10-29t115822](https://cloud.githubusercontent.com/assets/2786973/10816777/b6f86f32-7e35-11e5-8815-b304814126e0.png)

**Comment by slel** [comment]
Cool! Could you post a screenshot? In what version of Askbot is this available?

**Comment by evgenyfadeev** [comment]
I've just removed the user's name, so the button should be one line.
branches 0.7.x ,0.8.x, 0.9.x and master have this fix - no releases yet,
will be done soon though.

On Fri, Feb 26, 2016 at 12:25 AM, Samuel Lelièvre <notifications@github.com>
wrote:

> Cool! Could you post a screenshot? In what version of Askbot is this
> available?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/518#issuecomment-188995018>
> .
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev
