### ISSUE TITLE
Contributors on main page links to wrong page

### ISSUE THREAD

**Issue by bee2502** [ASKBOT/askbot-devel#520]
Contributors on main page https://ask.fedoraproject.org/en/questions/ links to 
https://ask.fedoraproject.org/en/question/8738/sticky-how-do-i-install-skype-on-fedora/

On further examining the HTML source for the page, I can see that the link is the last link of "Frequently Sought Posts" and this issue is a due to improper closing of attributes( for Skype)

     <h2>Frequently sought posts</h2> <ul> <li><a href="https://ask.fedoraproject.org/en/question   /9111/sticky-what-plugins-do-i-need-to-install-to-watch-movies-and-listen-to-music/" target="_blank">Music and video codecs</a></li> <li><a href="https://ask.fedoraproject.org/en/question/10217/sticky-how-do-i-install-adobe-flash-on-fedora/" target="_blank">Adobe Flash</a></li> <li><a href="https://ask.fedoraproject.org/en/question/8738/sticky-how-do-i-install-skype-on-fedora/" target="_blank"</a>Skype</li> </ul> </div> </div> <div id="contrib-users" class="box"> <h2 class="contributorback">Contributors</h2> <a class="avatar-box"
href="/en/users/13668/steve-hhh/"

Contributors on main page are generated from 
https://github.com/ASKBOT/askbot-devel/blob/29a926ebf42bab07086a366d5b5f1294b90141b3/askbot/templates/main_page.html

Sidebar is generated from 
https://github.com/ASKBOT/askbot-devel/blob/29a926ebf42bab07086a366d5b5f1294b90141b3/askbot/templates/main_page/sidebar.html

To solve, we need to edit file which generates "Frequently Sought Posts" with  proper identation

**Comment by evgenyfadeev** [comment]
Please contact the ask fedora site maintainers, this issue is not relevant
here imo.

On Tue, Nov 3, 2015 at 2:44 PM, Bhagyashree <notifications@github.com>
wrote:

> Contributors on main page https://ask.fedoraproject.org/en/questions/
> links to
>
> https://ask.fedoraproject.org/en/question/8738/sticky-how-do-i-install-skype-on-fedora/
>
> On further examining the HTML source for the page, I can see that the link
> is the last link of "Frequently Sought Posts" and this issue is a due to
> improper closing of attributes
>
>  <span class="page"><a href="/en/questions/scope:all/sort:activity-desc/page:455/" title="page 455">455</a></span><span class="next"><a href="/en/questions/scope:all/sort:activity-desc/page:2/" title="next page">next page &raquo;</a></span></div> <div class="clean"></div> </div> </div> <div id="ContentRight"> <div class="box"> <div class="box"> <h2>Guidelines</h2> <b>New to Ask Fedora? Please read the  <a href="https://fedoraproject.org/wiki/Ask_fedora_guidelines" target="_blank">guidelines</a>!</b> <h2> Sticky posts </h2> <b>Read <a href="https://ask.fedoraproject.org/questions/scope:all/sort:activity-desc/tags:guideline/page:1/" target="_blank">these posts</a> first! They help you use the forum better!</b> <h2>Frequently sought posts</h2> <ul> <li><a href="https://ask
>  .fedorap
>  roject.org/en/question/9111/sticky-what-plugins-do-i-need-to-install-to-watch-movies-and-listen-to-music/" target="_blank">Music and video codecs</a></li> <li><a href="https://ask.fedoraproject.org/en/question/10217/sticky-how-do-i-install-adobe-flash-on-fedora/" target="_blank">Adobe Flash</a></li> <li><a href="https://ask.fedoraproject.org/en/question/8738/sticky-how-do-i-install-skype-on-fedora/" target="_blank"</a>Skype</li> </ul> </div> </div> <div id="contrib-users" class="box"> <h2 class="contributorback">Contributors</h2> <a class="avatar-box"
> href="/en/users/13668/steve-hhh/"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/520>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by bee2502** [comment]
Sure.Thanks.
