### ISSUE TITLE
In dj-18, No matching distribution found for django-followit==0.2.0

### ISSUE THREAD

**Issue by hlj2722** [ASKBOT/askbot-devel#521]
(venv)root@hlj:~/aaaweb/askbot-devel# pip install askbot
Requirement already satisfied (use --upgrade to upgrade): askbot in ./venv/lib/python2.7/site-packages/askbot-0.9.0-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in ./venv/lib/python2.7/site-packages (from askbot)
Requirement already satisfied (use --upgrade to upgrade): django-celery>=3.0.11 in ./venv/lib/python2.7/site-packages (from askbot)
Requirement already satisfied (use --upgrade to upgrade): django-recaptcha>=1.0.3 in ./venv/lib/python2.7/site-packages (from askbot)
Requirement already satisfied (use --upgrade to upgrade): sanction==0.3.1 in ./venv/lib/python2.7/site-packages (from askbot)
Requirement already satisfied (use --upgrade to upgrade): html5lib==0.90 in ./venv/lib/python2.7/site-packages (from askbot)
Collecting django-followit==0.2.0 (from askbot)
  Could not find a version that satisfies the requirement django-followit==0.2.0 (from askbot) (from versions: 0.0.1, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0)
No matching distribution found for django-followit==0.2.0 (from askbot)

**Comment by evgenyfadeev** [comment]
Is this for for the branch supporting dj-18 ? If so - try using
django-followit from the git repo
and branch dj-18 also. This will be released some time soon, but so far
only available via github.

On Wed, Nov 4, 2015 at 6:45 PM, hlj2722 <notifications@github.com> wrote:

> (venv)root@hlj:~/aaaweb/askbot-devel# pip install askbot
> Requirement already satisfied (use --upgrade to upgrade): askbot in
> ./venv/lib/python2.7/site-packages/askbot-0.9.0-py2.7.egg
> Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4
> in ./venv/lib/python2.7/site-packages (from askbot)
> Requirement already satisfied (use --upgrade to upgrade):
> django-celery>=3.0.11 in ./venv/lib/python2.7/site-packages (from askbot)
> Requirement already satisfied (use --upgrade to upgrade):
> django-recaptcha>=1.0.3 in ./venv/lib/python2.7/site-packages (from askbot)
> Requirement already satisfied (use --upgrade to upgrade): sanction==0.3.1
> in ./venv/lib/python2.7/site-packages (from askbot)
> Requirement already satisfied (use --upgrade to upgrade): html5lib==0.90
> in ./venv/lib/python2.7/site-packages (from askbot)
> Collecting django-followit==0.2.0 (from askbot)
> Could not find a version that satisfies the requirement
> django-followit==0.2.0 (from askbot) (from versions: 0.0.1, 0.0.3, 0.0.4,
> 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0)
> No matching distribution found for django-followit==0.2.0 (from askbot)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/521>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by hlj2722** [comment]
Why the tagdoes not support Chinese in branch master?

**Comment by evgenyfadeev** [comment]
the django-followit of this version is available, closing the issue. There is a separate ticket for the language support of the tag.
