### ISSUE TITLE
Issue with Migrations for current master branch: User has no askbot_profile

### ISSUE THREAD

**Issue by albrnick** [ASKBOT/askbot-devel#561]
Hello!

I'm using django 1.8 and then need to use the latest master branch.  I'm trying to install as an add on app, to compliment the rest of my site.  However, when I try to run the migrations I get the following error:

$ python manage.py migrate

Running migrations:
  Rendering model states... DONE
  Applying askbot.0006_auto_20151220_0459...Marking claimed localized user profiles

  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/askbot/migrations/0006_auto_20151220_0459.py", line 33, in populate_claimed_localized_profiles
    profile = get_profile( user )
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/askbot/models/user_profile.py", line 14, in get_profile
    return user.askbot_profile
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/django/db/models/fields/related.py", line 470, in __get__
    self.related.get_accessor_name()
django.db.models.fields.related.RelatedObjectDoesNotExist: User has no askbot_profile.

Is this an error with the current code base?  Or am I doing something wrong?  I've added all the needed modules and settings, ran collectstatic and was running migrate.

**Comment by evgenyfadeev** [comment]
Please update the code from 'master' branch and try again.

**Comment by albrnick** [comment]
Thanks! :)  

I just tried, and got the error:

CommandError: Conflicting migrations detected (0012_rename_related_name_to_auth_user_from_Vote, 0008_auto_20160215_1515 in askbot).
To fix them run 'python manage.py makemigrations --merge

**Comment by evgenyfadeev** [comment]
Can't reproduce the "conflicting migrations issue", not sure what the reason is, but you might try to delete all the *.pyc files inside askbot/migrations (and anywhere else in askbot tree) and try again.

**Comment by albrnick** [comment]
Thanks for testing/trying! I will look into the issue!

**Comment by albrnick** [comment]
Just to followup, that conflicting migration no longer exists/this isn't an issue! :)
