### ISSUE TITLE
avatar.util renamed to avatar.utils in django-avatar

### ISSUE THREAD

**Issue by austinche** [ASKBOT/askbot-devel#567]
Askbot breaks when an avatar is uploaded and django-avatar (3.0.0) is installed. This appears to be due to https://github.com/grantmcconnaughey/django-avatar/commit/5cbd095cdabfce75440c7594d9e2080d34bd31cf
Editing `models/__init__.py` and replacing
`from avatar.util import get_primary_avatar` with
`from avatar.utils import get_primary_avatar` seems to work for me.

**Comment by krazybean** [comment]
+1 ran into the same issue.
