### ISSUE TITLE
Passwords in UTF8

### ISSUE THREAD

**Issue by MarcJose** [ASKBOT/askbot-devel#582]
Please use UTF8 for passwords and not ASCII only.. That increases the keyrange a lot which makes it more secure

> Auth exception: 'ascii' codec can't encode character u'\xa7' in position 12: ordinal not in range(128)

**Comment by evgenyfadeev** [comment]
I was unfortunately I was unable to reproduce this. If you have the time for that, could you provide the steps pls?

**Comment by evgenyfadeev** [comment]
Maybe this is related http://askbot.org/en/question/11522/unicodeencodeerror-at-questionsask/

try adding to your settings.py:

    import sys
    reload(sys)
    sys.setdefaultencoding('utf-8')

@MarcJose If this doesn't help and you are able to reproduce the issue with the latest version, please reopen this issue.
