### ISSUE TITLE
Posting links

### ISSUE THREAD

**Issue by MarcJose** [ASKBOT/askbot-devel#586]
Posting a link will be displayed as

> href="http://www.google.com/"><span< a=""> style="line-height: </span<>18.9px;">http://www.google.com/>

Something wrong with the HTML-Wrapping here..

**Comment by evgenyfadeev** [comment]
Some questions: with what editor, askbot version, how do you insert link to reproduce this?

**Comment by MarcJose** [comment]
I am using WYSWIG and Askbot v0.10.1 It might be the same editor-problem as in the other issue... messing up the HTML.
