### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by MarcJose** [ASKBOT/askbot-devel#587]
Enabling the markdown editor will prefill the answer-box with this:

`<br data-mce-bogus="1">`

**Comment by evgenyfadeev** [comment]
Enabling markdown after tinymce was enabled and draft post saved? I have not seen this with the default settings.

**Comment by MarcJose** [comment]
Yes, I enabled markdown in the settings:

![settings](https://cloud.githubusercontent.com/assets/7403918/14976812/368f966e-110f-11e6-821c-e6bbee69f440.jpg)
![editor](https://cloud.githubusercontent.com/assets/7403918/14976813/3693bc8a-110f-11e6-887f-fab7b5f31c3f.jpg)
