### ISSUE TITLE
Askbot creates lots of user groups

### ISSUE THREAD

**Issue by MarcJose** [ASKBOT/askbot-devel#591]
Looks like Askbot is creating a personel user group for every user. Not sure if that is on purpose or not.
The names are `_personal_XX` where XX is a number. This makes group management not easy especially with lots of users.

**Comment by evgenyfadeev** [comment]
each user has a _personal_<id number> group, this makes certain functions easier to implement.

Maybe partly the solution might be to improve the admin interface by filtering out the _private groups.
