### ISSUE TITLE
Unicode in tags

### ISSUE THREAD

**Issue by ebergmundur** [ASKBOT/askbot-devel#594]
It seems that it is not possible to use unicode in tags. 
Is there a known workaround or plan to allow that?

**Comment by evgenyfadeev** [comment]
Unicode tags work for me. Please post traceback or any other indication of error. What database do you have?

**Comment by ebergmundur** [comment]
I'm using Postgres with UTF-8, but the problem seems to be related to validation. Possibly in JS. 
The problematic chars are the Icelandic ones like á, í, ú, ý, ó, þ, æ, ö.

I tried to change the tag settings from **tree** to **user input** and that works fine. 
So I guess the problem lies in the tree input interface. 

Using only single level tags can be a workaround but I was hoping to be able to use the tree. 
I'll take a closer look at the tree validation process. 

Tags I've been using to test are:  "ýmislegt" and "þýðingar" 

BTW. I've got access to the translation to Icelandic and will upload translation soon if I get some time to finish it.

**Comment by evgenyfadeev** [comment]
Thank you, that helps, I will test this tomorrow.

**Comment by ebergmundur** [comment]
Found the culprit
It's in the cleanTag function in media/js/utils.js 
by setting 
`tag_regex = new RegExp("^[\wþæöýðáíúóé][\w+.#-þæöýðáíúóé]+$");`
I was able to use any Icelandic character in the tag_name

There may be a better way but this works for me now by using js files from my own skin directory.

**Comment by evgenyfadeev** [comment]
I don't see a reliable way to make a unicode regex portable between python and js, probably will add ajax tag validation.

**Comment by evgenyfadeev** [comment]
@ebergmundur thanks for the hints, fixed now.
