### ISSUE TITLE
master branch deadlocks django 1.8

### ISSUE THREAD

**Issue by albrnick** [ASKBOT/askbot-devel#599]
Hello!

I'm using django 1.8 and using the latest master branch. I'm trying to install as an add on app, to compliment the rest of my site. I've run into an issue where django is deadlocked, even doing simple things like 'manage.py shell'.  I've traced it down to the populate method in django/apps/registry.py being called from within itself (ie twice in the stack), which is deadlocking the 'self._lock' call in populate.

I've tracked this down to the init_badges() line in askbot/apps.py shown below:

`
class AskbotConfig(AppConfig):
    name = 'askbot'
    verbose_name = 'Askbot Q&A platform'

    def ready(self):
        from askbot.models import badges
        try:
            badges.init_badges()
        except:
            pass

        import followit
        user_model = get_user_model()
        followit.register(user_model)
`

When I comment out the 'badges.init_badges()' line, the deadlock goes away.  Where should I move this logic to?

**Comment by albrnick** [comment]
Oh, and to show the stacktrace on the deadlock (some of the line numbers may be off due to the extra debuging print statements I put in :)

Current thread 0x00007f280e07d740 (most recent call first):
  File "site-packages/django/apps/registry.py", line 71 in populate
  File "site-packages/django/db/models/base.py", line 1712 in model_unpickle
  File "site-packages/redis_cache/serializers.py", line 42 in deserialize
  File "site-packages/redis_cache/backends/base.py", line 186 in deserialize
  File "site-packages/redis_cache/backends/base.py", line 199 in get_value
  File "site-packages/redis_cache/backends/base.py", line 248 in get
  File "site-packages/redis_cache/backends/base.py", line 32 in wrapped
  File "site-packages/keyedcache/__init__.py", line 285 in cache_get
  File "site-packages/askbot/deps/livesettings/models.py", line 44 in find_setting
  File "site-packages/askbot/deps/livesettings/values.py", line 337 in _setting
  File "site-packages/askbot/deps/livesettings/values.py", line 368 in _value
  File "site-packages/askbot/deps/livesettings/values.py", line 464 in value
  File "site-packages/askbot/conf/settings_wrapper.py", line 75 in get_value
  File "site-packages/askbot/conf/settings_wrapper.py", line 68 in __getattr__
  File "site-packages/askbot/models/badges.py", line 593 in __init__
  File "site-packages/askbot/models/badges.py", line 982 in get_badge
  File "site-packages/askbot/models/badges.py", line 993 in init_badges
  File "site-packages/askbot/apps.py", line 11 in ready
  File "site-packages/django/apps/registry.py", line 115 in populate
  File "site-packages/django/__init__.py", line 18 in setup
  File "site-packages/django/core/management/__init__.py", line 325 in execute
  File "site-packages/django/core/management/__init__.py", line 351 in execute_from_command_line
  File "manage.py", line 10 in <module>

**Comment by evgenyfadeev** [comment]
Hi @albrnick, would you be able to come up with a "settings.py" that you could share to reproduce this?

**Comment by albrnick** [comment]
Of course!  I've added the following lines to my settings.py:
                                                                                                         
#Begin askbot settings                                                                                           
TINYMCE_COMPRESSOR = True
TINYMCE_SPELLCHECKER = False
TINYMCE_JS_ROOT = os.path.join(STATIC_ROOT, 'default/media/tinymce/')
from .askbot import *
 # needs to be here vs .askbot due to STATIC_URL                                                                   
TINYMCE_DEFAULT_CONFIG['content_css'] = STATIC_URL + 'default/media/style/tinymce/content.css'

#End askbot settings                                                                                             
                                                                                                      

**_And then the askbot.py settings:_**


import os

                                                                                                      
IMAP_HOST = ''
IMAP_HOST_USER = ''
IMAP_HOST_PASSWORD = ''
IMAP_PORT = ''
IMAP_USE_TLS = False


ASKBOT_LANGUAGE_MODE = 'single-lang' #'single-lang', 'url-lang' or 'user-lang'                                    


JINJA2_EXTENSIONS = (
    'compressor.contrib.jinja2ext.CompressorExtension',
)


ASKBOT_ALLOWED_UPLOAD_FILE_TYPES = ('.jpg', '.jpeg', '.gif', '.bmp', '.png', '.tiff')
ASKBOT_MAX_UPLOAD_FILE_SIZE = 1024 * 1024 #result in bytes                                                        
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

LIVESETTINGS_CACHE_TIMEOUT = 6000
CACHE_MIDDLEWARE_ANONYMOUS_ONLY = True
CACHE_MIDDLEWARE_SECONDS = 600


ASKBOT_URL = 'forum/' #no leading slash, default = '' empty string                                                
 #nla ASKBOT_TRANSLATE_URL = True #translate specific URLs                                                         
_ = lambda v:v #fake translation function for the login url                                                       
 #nla LOGIN_URL = '/%s%s%s' % (ASKBOT_URL,_('account/'),_('signin/'))                                              
 #nla LOGIN_REDIRECT_URL = ASKBOT_URL #adjust if needed                                                            
 #note - it is important that upload dir url is NOT translated!!!                                                  
 #also, this url must not have the leading slash                                                                   
ALLOW_UNICODE_SLUGS = False
ASKBOT_USE_STACKEXCHANGE_URLS = False #mimic url scheme of stackexchange                                          

 #Celery Settings                                                                                                  
BROKER_TRANSPORT = "djkombu.transport.DatabaseTransport"
CELERY_ALWAYS_EAGER = True

import djcelery
djcelery.setup_loader()

 #nla CSRF_COOKIE_NAME = 'askbot_csrf'                                                                             

RECAPTCHA_USE_SSL = True
 #! nla - do we want this?                                                                                         
NOCAPTCHA = True

 #HAYSTACK_SETTINGS                                                                                                
ENABLE_HAYSTACK_SEARCH = False


 #TINYMCE_JS_URL = STATIC_URL + 'default/media/js/tinymce/tiny_mce.js'                                             
 # nla - put back?!                                                                                                
TINYMCE_COMPRESSOR = False
TINYMCE_SPELLCHECKER = False
STATIC_ROOT2 =  '/home/user/html/www./static/'  # nla - Hack due to not having access to STATIC_ROOT          
STATIC_URL2 = '/static/'
TINYMCE_JS_ROOT = os.path.join(STATIC_ROOT2, 'default/media/tinymce/')
TINYMCE_JS_URL = STATIC_URL2 + 'default/media/tinymce/tiny_mce.js'
TINYMCE_DEFAULT_CONFIG = {
    'plugins': 'askbot_imageuploader,askbot_attachment',
    'convert_urls': False,
    'theme': 'advanced',
    'force_br_newlines': True,
    'force_p_newlines': False,
    'forced_root_block': '',
    'mode' : 'textareas',
    'oninit': "TinyMCE.onInitHook",
    'plugins': 'askbot_imageuploader,askbot_attachment',
    'theme_advanced_toolbar_location' : 'top',
    'theme_advanced_toolbar_align': 'left',
    'theme_advanced_buttons1': 'bold,italic,underline,|,bullist,numlist,|,undo,redo,|,link,unlink,askbot_imageupl\
oader,askbot_attachment',
    'theme_advanced_buttons2': '',
    'theme_advanced_buttons3' : '',
    'theme_advanced_path': False,
    'theme_advanced_resizing': True,
    'theme_advanced_resize_horizontal': False,
    'theme_advanced_statusbar_location': 'bottom',
    'editor_deselector': 'mceNoEditor',
    'width': '100%',
    'height': '250'
}

#delayed notifications, time in seconds, 15 mins by default                                                       
NOTIFICATION_DELAY_TIME = 60 * 15

GROUP_MESSAGING = {
    'BASE_URL_GETTER_FUNCTION': 'askbot.models.user_get_profile_url',
    'BASE_URL_PARAMS': {'section': 'messages', 'sort': 'inbox'}
}

COMPRESS_JS_FILTERS = []
COMPRESS_PARSER = 'compressor.parser.HtmlParser'
JINJA2_EXTENSIONS = ('compressor.contrib.jinja2ext.CompressorExtension',)

VERIFIER_EXPIRE_DAYS = 3
AVATAR_AUTO_GENERATE_SIZES = (16, 32, 48, 128)

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

JINJA2_TEMPLATES = ('captcha',)

#TODO - REMOVE LATER!                                                                                            
#nla - I think he removed! :)                                                                                   
CACHE_MIDDLEWARE_ANONYMOUS_ONLY = True
LOGIN_REDIRECT_URL = ASKBOT_URL


#TODO - TEsting only, remove later!                                                                              
ASKBOT_SELF_TEST = False

**Comment by evgenyfadeev** [comment]
Hmm, thanks, but could you post a version of settings.py that is self-sufficient to reproduce the issue?

**Comment by albrnick** [comment]
Unfortunately it's in an existing site, with like 20 other apps, most of which are custom/it wouldn't run. :(  In a week or so I could try to setup a new site and try to get a bare bones site that would replicate this issue. (BTW, I got the deadlock on the 'manage.py collectstatic')  

Dunno if too obscure, but from what I can tell, here is what is happening:

Django is calling it's registry.populate function with the list of installed apps

File "site-packages/django/apps/registry.py", line 115 in populate

<pre>
   def populate(self, installed_apps=None):
        """                                                                                                       
        Loads application configurations and models.                                                              
        This method imports each application module and then each model module.                                   
        It is thread safe and idempotent, but not reentrant.                                                      
        """
        if self.ready:
            return

        with self._lock:
            if self.ready:
                return

....[skipping code]...

            for app_config in self.get_app_configs():
                app_config.ready()   # <----- HERE!!!

            self.ready = True
</pre>

Which calls this code

  File "site-packages/askbot/apps.py", line 11 in ready
<pre>
class AskbotConfig(AppConfig):
    name = 'askbot'
    verbose_name = 'Askbot Q&A platform'

    def ready(self):
        from askbot.models import badges
        try:
            badges.init_badges() # <----- HERE!!!
        except:
            pass

</pre>

Which is ultimately instantiating Badges objects here:

  File "site-packages/askbot/models/badges.py", line 982 in get_badge

<pre>
def get_badge(name=None):
    """Get badge object by name, if none matches the name                                                         
    raise KeyError                                                                                                
    """
    key = slugify(name)
    print BADGES
    print key
    print BADGES[key]
    return BADGES[key]()    # <!------ HERE!!!
</pre>

And I don't fully understand the logic of the settings_wrapper / live settings bit, but it's pulling a class from the redis cache, which when deserializing / unpickling, calls:

  File "site-packages/django/db/models/base.py", line 1712 in model_unpickle

<pre>
def model_unpickle(model_id, attrs, factory):
    """                                                                                                           
    Used to unpickle Model subclasses with deferred fields.                                                       
    """
    if isinstance(model_id, tuple):
        if not apps.ready:
            apps.populate(settings.INSTALLED_APPS)   # <!------ HERE!!!
        model = apps.get_model(*model_id)
</pre>

Which now in turns takes the ugly turn of:

File "site-packages/django/apps/registry.py", line 115 in populate

<pre>
   def populate(self, installed_apps=None):
        """                                                                                                       
        Loads application configurations and models.                                                              
        This method imports each application module and then each model module.                                   
        It is thread safe and idempotent, but not reentrant.                                                      
        """
        if self.ready:
            return

        with self._lock:   # <----- HERE!!!
</pre>

And it deadlocks up there, as the self._lock is held from the first time we entered this function. 

Let me see if I can find what class it is trying to deserialize...

EUGH!  Of course now it isn't locking up..  <Sigh>  I'll leave this here, so I can try to reproduce with a fresh install..

**Comment by albrnick** [comment]
Oh wow, looks like there is a limit to the # of lines!  So continuing...

And I don't fully understand the logic of the settings_wrapper / live settings bit, but it's pulling a class from the redis cache, which when deserializing / unpickling, calls:

  File "site-packages/django/db/models/base.py", line 1712 in model_unpickle

<pre>
def model_unpickle(model_id, attrs, factory):
    """                                                                                                           
    Used to unpickle Model subclasses with deferred fields.                                                       
    """
    if isinstance(model_id, tuple):
        if not apps.ready:
            apps.populate(settings.INSTALLED_APPS)   # <------ HERE!!!
        model = apps.get_model(*model_id)
</pre>

Which now in turns takes the ugly turn of:

File "site-packages/django/apps/registry.py", line 115 in populate

<pre>
   def populate(self, installed_apps=None):
        """                                                                                                       
        Loads application configurations and models.                                                              
        This method imports each application module and then each model module.                                   
        It is thread safe and idempotent, but not reentrant.                                                      
        """
        if self.ready:
            return

        with self._lock:   # <----- HERE!!!
</pre>

And it deadlocks up there, as the self._lock is held from the first time we entered this function. 

Let me see if I can find what class it is trying to deserialize...

EUGH!  Of course now it isn't locking up..  <Sigh>  I'll leave this here, so I can try to reproduce with a fresh install..

**Comment by albrnick** [comment]
Cool, it's back! :)

Looks like the 'model_id' that is passed into model_unpickle is:

('livesettings', 'Setting')

**Comment by evgenyfadeev** [comment]
I was able to reproduce this with redis cache and having non-default values of the badge settings.
