### ISSUE TITLE
django_settings.ATOMIC_REQUESTS not set when trying to use celery

### ISSUE THREAD

**Issue by albrnick** [ASKBOT/askbot-devel#601]
Hello!

I was trying to enable celery and found that when setting:

`CELERY_ALWAYS_EAGER = False`

I got an AttributeError:

`'Settings' object has no attribute 'ATOMIC_REQUESTS'`

in the file:

`askbot/utils/transaction.py in defer_celery_task`

Which I fixed by adding:

ATOMIC_REQUESTS = False

in the settings.py file.

Just passing the fix along! = )

**Comment by evgenyfadeev** [comment]
This will make celery tasks not run, for example - view counts won't be incremented. The `defer_celery_task` in the master branch needs to be fixed.

**Comment by evgenyfadeev** [comment]
@albrnick could you try the current master? I've modified the offending function in commit bf056a75e1139fee613c2c61cb92d70fa70a02c4

If this works could you close the issue pls?

**Comment by albrnick** [comment]
That worked!  I no longer have to set ATOMIC_REQUESTS. :)

Thanks!
