### ISSUE TITLE
Karma page is broken

### ISSUE THREAD

**Issue by gs-ajain** [ASKBOT/askbot-devel#605]
When I hit `/users/14/userName/?sort=reputation` the page is broken with following error:

     Django Version:	1.8.14
     Exception Type:	NameError
     Exception Value:	
     global name 'datetime' is not defined
     Exception Location:	/home/root/askbot/askbot/views/users.py in format_graph_data, line 1012

**Any resolution? Am I missing any dependency?**

![askboterror](https://cloud.githubusercontent.com/assets/7457667/17413223/f4bb220c-5a9d-11e6-8fc0-ec76ca9776f2.png)

**Comment by gs-ajain** [comment]
does this commit fixes this?  https://github.com/ASKBOT/askbot-devel/commit/b37b225e4f7495ecae87f6968d12d1d0fb60c20c

**Comment by evgenyfadeev** [comment]
yes - please try that.

**Comment by gs-ajain** [comment]
Yup it is working now. Pulled latest code.
