### ISSUE TITLE
Please rework notifications (particularly, don't punish users for making edits)

### ISSUE THREAD

**Issue by mattdm** [ASKBOT/askbot-devel#674]
To be blunt, notifications are basically useless as they stand, except on very small sites.

At the very least, notifications for answers and comments should be separated from other things.

The worst thing, though, is how I get notifications for every activity related to any question I ever edit. This is a huge disincentive to help. If I see a spelling error on Wikipedia or Stack Exchange, I'll fix it. If I do that here, I'm punished by having my notification queue overwhelmed by things I don't care about — if I fix punctuation in some question, I don't need to know anything more about it (except, maybe, if someone rolls back my edit — but even that shouldn't interfere with my actual "my stuff" notifications).

**Comment by evgenyfadeev** [comment]
Fixed in 323cf5e379a0a96426a378784c8d57d41f885fad
