### ISSUE TITLE
Invalid field name(s) given in select_related: 'gravatar'. Choices are: askbot_profile, userpasswordqueue

### ISSUE THREAD

**Issue by ZuluPro** [ASKBOT/askbot-devel#682]
When I go to ``/queue-moderation/``

I have : ``Invalid field name(s) given in select_related: 'gravatar'. Choices are: askbot_profile, userpasswordqueue``

I didn't dig a lot, but just remove this [line](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/views/moderation.py#L159) seems to fix.

**Comment by evgenyfadeev** [comment]
Thank you! Fixed in commit 8b3781f3d1ca73d02c858c813ede6eecc73fcc03
