### ISSUE TITLE
unable to signin [ask fedora]

### ISSUE THREAD

**Issue by Raffaello** [ASKBOT/askbot-devel#691]
When i am sign in in is not recognizing me own email / username and the system is asking me to sign up, but obviously is not possible because my own email is already present.

here my profile:
https://ask.fedoraproject.org/en/users/4950/raffaello/

please help me / fix it.

thank you

**Comment by evgenyfadeev** [comment]
@Raffaello  please address this to the admins of ask.fedoraproject.org, I'm only a developer of this software. I will ping someone who might direct this inquiry to a proper person.

**Comment by nirik** [comment]
@Raffaello Can you open a ticket at https://pagure.io/fedora-infrastructure and we can try and assist you from there. In particular it would be good to know how you were logging in before (what provider) and how you are trying now... thanks!

**Comment by Raffaello** [comment]
@nirik Ok. 
Cooool! I am with the bigs now! :smile: 
I hope there is a way to contribute and learn something more! 
thank you.
