### ISSUE TITLE
How to integrate Math Symbol editor 

### ISSUE THREAD

**Issue by satish18** [ASKBOT/askbot-devel#694]
I have found a plugin which converts Math symbols into a latex code but i am unable to pass that values to the markdown  editor. Please help me on this issue

**Comment by evgenyfadeev** [comment]
Hi Satish, Mathjax is supported, please look here https://github.com/ASKBOT/askbot-devel/blob/master/askbot/doc/source/mathjax.rst and search Mathjax on the Askbot support forum.
