### ISSUE TITLE
Proposed change: allow configuration of DB host and port when running askbot-setup

### ISSUE THREAD

**Issue by MichaelPereira** [ASKBOT/askbot-devel#712]
Hi,

I would like to contribute some changes that would make it possible to easily run askbot in a [docker-compose environment](https://docs.docker.com/compose/overview/) (which would reduce the deployment steps for a local testing environment to one command `docker-compose up`).

A pre-requisite for the change above, is to be able to configure the database host and port for askbot via the `askbot-setup` configuration. This utility is really nice to quickly setup a new askbot configuration without the need for maintaining different templates and I would like to take advantage of it to even provide docker-compose alternative files with different databases (postgresql, mysql, etc).

I've already made the change in [a branch of my fork](https://github.com/MichaelPereira/askbot-devel/tree/configure-db-host), would you like me to create a pull request for that change? With the next changes after this one to properly dockerize the application, it will be easier to resolve issues like #706.

Regards,
Michael

**Comment by evgenyfadeev** [comment]
Hi Michael, could you please make a PR for that? Would be great to support the db port and host in the askbot-setup. Could you please test that it works with the default empty values too?

**Comment by MichaelPereira** [comment]
Yes, I set them to not be required for that purpose. I will create the pull request once I rebase my branch over the newer master.
