### ISSUE TITLE
django-avatar version is very old

### ISSUE THREAD

**Issue by omerfarukdogan** [ASKBOT/askbot-devel#766]
In askbot-requirements.txt file, `django-avatar==2.2.1` is required. But when this version is used, `user_calculate_avatar_url` method constantly prints 'Using deprecated version of django-avatar' logs. Either a newer version of django-avatar should be required, or the log should be disabled.

**Comment by martin-bts** [comment]
That is oddly arbitrary. Askbot is a meseum of ancient code. Deprecated means this is still one of the more recent pieces of software that can be found in Askbot. :-)

**Comment by martin-bts** [comment]
This particular issue does not exist in the master branch.
