### ISSUE TITLE
Publish a new release 0.10.2

### ISSUE THREAD

**Issue by abitrolly** [ASKBOT/askbot-devel#774]
HI @evgenyfadeev. Is it possible to release version 0.10.2 to see what bugs were fixed over the time and what is already available in `master` compared to old installs?

**Comment by sebastian-philipp** [comment]
Right now, installing [0.10.2](https://pypi.org/project/askbot/0.10.2/) from pip is broken, as it contains #735 

Installing the Python 3 version also failes, cause it doesn't include #722

**Comment by martin-bts** [comment]
Askbot version 0.11.1 is [available at Pypi](https://pypi.org/project/askbot/). This issue seems resolved.

**Comment by abitrolly** [comment]
@martin-bts iep, thanks for the heads up.

**Comment by abitrolly** [comment]
Although it is not clear what repo code corresponds to this version, because the release is not tagged - https://github.com/ASKBOT/askbot-devel/tags
