### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by AlliterativeAlice** [ASKBOT/askbot-devel#779]
The address for documentation, https://askbot.org/doc/index.html, currently 404s so it isn't possible to access instructions on how to install/use Askbot except by using archived versions of the page.

**Comment by HypotheticalMan** [comment]
Bump...

It would be great if we could get this link fixed so people can get to the documentation page and use the documentation to get Askbot set up and could learn how to administer their instance of Askbot.

**Comment by StingRayZA** [comment]
you can build your own copy of the docs:

(You will need a copy of https://www.sphinx-doc.org/en/master/usage/installation.html first...)

```
git clone git@github.com:ASKBOT/askbot-devel.git
cd askbot-devel/askbot/doc
make html
```
You'll find the docs in build/html

**Comment by elbraulio** [comment]
@StingRayZA can you share those docs?

**Comment by StingRayZA** [comment]
[askbot-docs.tar.gz](https://github.com/ASKBOT/askbot-devel/files/2643508/askbot-docs.tar.gz)
Here's a tarball of the file I've built based on a fresh clone of master...

**Comment by ir4y** [comment]
Hi @evgenyfadeev !
Is it possible to get docs back?

**Comment by AlliterativeAlice** [comment]
Closing since https://askbot.org/doc/index.html seems to be working again
