### ISSUE TITLE
No obvious way to stop 'Unanswered questions' emails

### ISSUE THREAD

**Issue by takluyver** [ASKBOT/askbot-devel#796]
Having an account on ROS answers (running askbot 0.10.2), I started getting automatic emails with a list of unanswered questions.

Firstly, these emails don't have an 'unsubscribe' link anywhere that I can see. I expect any automated regular email to have this.

Secondly, when I go to the email alerts settings page on the site, none of the available settings clearly relate to the 'unanswered questions' email:

![Screenshot from 2019-06-20 10-19-30](https://user-images.githubusercontent.com/327925/59837524-4ae41980-9345-11e9-94d3-60e4ac9c4580.png)

Looking at [send_unanswered_question_reminders.py](https://github.com/ASKBOT/askbot-devel/blob/master/askbot/management/commands/send_unanswered_question_reminders.py), I see it filters the list by `user.get_tag_filtered_questions`. So maybe setting the tag filter to 'only interesting tags' will stop this if there are no 'interesting' tags. But this isn't very obvious.

(I would also rather new automatic emails were opt-in rather than opt-out, even if there is an obvious way to opt out. But maybe that's up to the site administrators rather than the code.)

**Comment by evgenyfadeev** [comment]
fixed in 5c871cc108516f388d46629695111ca991bbf4c4 will be deployed on your site tomorrow
