### ISSUE TITLE
Rename "Your Answer" to "Suggest a solution"

### ISSUE THREAD

**Issue by mikekaganski** [ASKBOT/askbot-devel#797]
On ask.LibreOffice.org, we see a lot of users confusing the site with a forum, and thinking that using the Answer box, they are answering someone other's answer. It can't be stopped, because new users don't read site rules etc., they just answer someone on that page.

The proposal is to rename the "Your Answer" box (WORDS_YOUR_ANSWER in askbot/conf/words.py) into something like "Propose Your Solution". This would somewhat clarify that "your answer" is not "some" answer, but something to try to solve original problem.

Possibly WORDS_BE_THE_FIRST_TO_ANSWER_THIS_QUESTION there should be changed accordingly, too.

Thank you!

**Comment by martin-bts** [comment]
On the StackExchange network the answer box's headline is also "Your Answer" and it seems to work well enough.

This looks like a site specific issue to me.

**Comment by mikekaganski** [comment]
> On the StackExchange network the answer box's headline is also "Your Answer" and it seems to work well enough.
> 
> This looks like a site specific issue to me.

I disagree.

Rather, the StackExchange usage is rather site-specific, relying on quite harsh treatment of not following the rules. But the bot engine imo can't be made with several assumptions necessary for that, like (1) site being product-neutral (necessary to not create negative perception of a product as a collateral damage); (2) site being that much popular, having a luxury to allow itself welcome newcomers with some negative experience.

So, *in general*, appealing to a high-profile site as a "general rule" is incorrect imo.

**Comment by evgenyfadeev** [comment]
@mikekaganski - as you've noted it is possible to achieve via adjusting the settings, however - managing the ask.libreoffice.org is beyond the scope of this repository. Please discuss this with the stakeholders of that specific site - here we cannot make the decisions for them:).
