### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'get'

### ISSUE THREAD

**Issue by EvanCarroll** [ASKBOT/askbot-devel#832]
After I run `setup.py develop`, I get the following when I run `python3 askbot-setup`

```
ubuntu@askbot:~/askbot-devel$ askbot-setup 

Deploying Askbot - Django Q&A forum application
Problems installing? -> please email admin@askbot.org

To CANCEL - hit Ctr-C at any time

Traceback (most recent call last):
  File "/usr/local/bin/askbot-setup", line 11, in <module>
    load_entry_point('askbot==0.10.2', 'console_scripts', 'askbot-setup')()
  File "/usr/local/lib/python3.6/dist-packages/askbot-0.10.2-py3.6.egg/askbot/deployment/__init__.py", line 216, in __call__
    directory = path_utils.get_install_directory(force=options.get('force')) # i.e. ask the user
AttributeError: 'Namespace' object has no attribute 'get'
```

**Comment by martin-bts** [comment]
This bug was fixed in https://github.com/ASKBOT/askbot-devel/commit/a0cf4b029e3c035a8555e30de5de20eb3ad926cc

**Comment by EvanCarroll** [comment]
Shouldn't that also be ported to the 0.11.x branch then? https://github.com/ASKBOT/askbot-devel/blob/0.11.x/askbot/deployment/__init__.py#L216

**Comment by martin-bts** [comment]
The installer sees many changes at the moment. https://github.com/ASKBOT/askbot-devel/pull/827 takes care of this issue.

**Comment by martin-bts** [comment]
The current merging candidate that will resolve this issue is now https://github.com/ASKBOT/askbot-devel/pull/849

**Comment by martin-bts** [comment]
This refers to a piece of code that is no longer part of Askbot. I suggest closing this issue, because it is not relevant anymore.
