### ISSUE TITLE
0.11.x homepage UI is... not beautiful

### ISSUE THREAD

**Issue by piggybit** [ASKBOT/askbot-devel#850]
installed 0.11.x but homepage UI is not like the old version.
Anything wrong i have done?

![Screenshot from 2019-10-19 08-57-06](https://user-images.githubusercontent.com/55419584/67136402-f481db80-f24f-11e9-8ac6-c8276121501c.png)

**Comment by evgenyfadeev** [comment]
Hey @piggybit it actually says: "if you do not see page styling, ... or use --insecure flag with the runserver command".

**Comment by piggybit** [comment]
tks!
