### ISSUE TITLE
 No posts for moderation (moderation-queue)

### ISSUE THREAD

**Issue by Toxu-ru** [ASKBOT/askbot-devel#859]
If you set the moderation of links, there are no posts for moderation.

- Install the script. Create an administrator and a regular user.
- Turn on moderation links. And from the admin add a question.
- Let the user respond (+ link)

 
When the moderation icon appears in the site header, click on it. There are no posts for moderation. The icon in the header is lit, there are no posts.

**Comment by piggybit** [comment]
i believe you can post it in English.
Btw, i might want to ask if you have any difficulty for unaccent search in your project?

**Comment by Toxu-ru** [comment]
No, I don't have any problems finding it. So far, I'm just studying the script and determining whether it fits or not. 

Similarly, I have some comments about XSS, but I will write about them later. 

Now I'm trying to solve the problem of moderation of posts with links. Why I don't see messages. Hmmm

**Comment by piggybit** [comment]
You are using 2016 version with python 2?
I am using python 3 version.

**Comment by Toxu-ru** [comment]
Yes, I'm using 2.7. The latest release from the repository. 
Which version 3 do you use (more accurately)?

**Comment by piggybit** [comment]
Sorry, it was my mistake, it's not python3 but 2 instead.

**Comment by Toxu-ru** [comment]
There should be 2 posts-moderation...
![1](https://user-images.githubusercontent.com/6613623/77535527-c746f280-6eab-11ea-83c9-9dc664a27aa5.jpg)
