### ISSUE TITLE
Fix Askbot Y2k20 bug: short-form dates for 2020 show as '0 instead of '20

### ISSUE THREAD

**Issue by slel** [ASKBOT/askbot-devel#862]
Following reports

- on Ask Sage

    ask.sagemath.org Y2k20 bug
    https://ask.sagemath.org/question/49411

- on Ask Askbot

    Date abbreviation for 2020 shown as `'0`
    https://askbot.org/en/question/18343

**Comment by evgenyfadeev** [comment]
Gotcha, thanks. Will apply on the weekend.

**Comment by dajare** [comment]
Hi @evgenyfadeev - any chance of taking this forward? We're waiting for it at AskLibreOffice, too.... (And it's August!)

**Comment by evgenyfadeev** [comment]
@dajare @slel will be fixed asap

**Comment by evgenyfadeev** [comment]
It's fixed in the master branch and 0.7.x - 0.9.x branches.

**Comment by slel** [comment]
Can you deploy on [Ask Askbot](https://askbot.org)?

This would showcase the result and encourage other
Askbot-powered sites to update.

**Comment by dajare** [comment]
@slel I see you're still waiting for it at AskSage. I'm greatly relieved to report it has already been rolled out at AskLibreOffice. Thanks for your initiative on fixing this.
