### ISSUE TITLE
askbot.deps' has no attribute 'livesettings'

### ISSUE THREAD

**Issue by mschnepf** [ASKBOT/askbot-devel#898]
I try to update our askbot instance from version 0.10.2 to 0.11.1 . Thereby, I get the error in the apache2 log by accessing the instance via HTTP:
```
mod_wsgi (pid=11): Failed to exec Python script file '/opt/b2-askbot/django.wsgi'.
mod_wsgi (pid=11): Exception occurred processing WSGI script '/opt/b2-askbot/django.wsgi'.
Traceback (most recent call last):                                              
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)                                                
AttributeError: module 'askbot.deps' has no attribute 'livesettings' 
```
It seems that the directory `askbot/deps/livesettings/` disappeared from switching branch 0.10.x to 0.11.x. Is that a known issue?

**Comment by evgenyfadeev** [comment]
I've downloaded the 0.11.1 from pypi and tried to find an import from askbot.deps.
Could not find any place except  where a line is commented out in the template for the urls.py file - 
testproject/testproject/urls.py

Could not find any references to that import elsewhere.

Maybe the culprit is your INSTALLED_APPS variable in the settings.py file?

**Comment by evgenyfadeev** [comment]
Another possibility is that your apache hash python paths mixing the two versions. Usually that can be detected by printing contents of  "sys.path" or logging it.

This is often the case if your site works with development server "python manage.py runserver" but fails with apache mod_python or nginx + uwsgi.

**Comment by evgenyfadeev** [comment]
Assuming that you've figured this out, please let me know if I missed something.
