### ISSUE TITLE
Login page shows 404.

### ISSUE THREAD

**Issue by EvanCarroll** [ASKBOT/askbot-devel#911]
When I boot up on a new install, even after having created a super user, I get a 404 when I click on the account login button.

http://localhost:3000/accounts/login

**Comment by EvanCarroll** [comment]
Guessing this is related to https://github.com/ASKBOT/askbot-devel/commit/489478234eacc6c3b21ffb070d6acf7ecc21eac0

**Comment by evgenyfadeev** [comment]
Closed in fa9cb414edbb07d5819e2c4775d4da404779095d
