### ISSUE TITLE
Incorrect Dependency Handle for django-appconf

### ISSUE THREAD

**Issue by QuantumOracle** [ASKBOT/askbot-devel#919]
I have the correct version of django-appconf installed. However, the installer keeps installing 1.0.3 and requiring 1.0.5. 

Installed /usr/local/lib/python3.10/dist-packages/askbot-0.11.3-py3.10.egg
Processing dependencies for askbot==0.11.3
error: django-appconf 1.0.3 is installed but django-appconf>=1.0.5 is required by {'django-avatar'}

/Askbot/askbot-devel$ pip install django-appconf==1.0.5
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: django-appconf==1.0.5 in /usr/local/lib/python3.10/dist-packages (1.0.5)Requirement already satisfied: django in /usr/lib/python3/dist-packages (from django-appconf==1.0.5) (3.2.12)

**Comment by Pavel-Sayekat** [comment]
encountered that on ubuntu 20.04 with python3.8
