### ISSUE TITLE
OpenID Connect login

### ISSUE THREAD

**Issue by brunobastosg** [ASKBOT/askbot-devel#926]
Is it possible to use some third-party library (like [mozilla-django-oidc](https://mozilla-django-oidc.readthedocs.io))?

Or it would require changes in askbot's code anyway?

**Comment by brunobastosg** [comment]
Just saw that there is code for OIDC: https://github.com/ASKBOT/askbot-devel/tree/master/askbot/deps/django_authopenid/protocols/oidc

Is it working? I don't see any login provider for OIDC here https://github.com/ASKBOT/askbot-devel/blob/3ac68d76c8b94ac7f51fc2d7dac5ff43e5229781/askbot/conf/login_providers.py

**Comment by evgenyfadeev** [comment]
So far I have it tested via configuring a ASKBOT_CUSTOM_AUTH_MODULE, which is a .py file containing settings:

BIG_BUTTON = True
ORDER_NUMBER = 1
NAME = 'AskbotOkta'
ICON_MEDIA_PATH = 'images/jquery-openid/okta.png'
DISPLAY_NAME = 'Okta'
TYPE = 'oidc'
TRUST_EMAIL = True
TOOLTIP_TEXT = 'Sign in via Okta'
EXTRA_TOKEN_NAME = 'Okta login name and password'
OIDC_AUDIENCE = 'api://default'
OIDC_PROVIDER_URL = 'https://<your app>/oauth2/default'
OIDC_CLIENT_ID = '<your client id>'
OIDC_CLIENT_SECRET = '<your client secret>'

It is working for me with OKTA, not  tested with any other providers yet.

You can examine how this module is interpreted and try to define it accordingly. 

It is possible that some  modifications to the oidc flow might be needed to accomodate other OIDC providers, but those changes should be acceptable for all providers.

**Comment by brunobastosg** [comment]
Great! Thanks for the info! I'll try it.

**Comment by brunobastosg** [comment]
Hey, evgeny. It worked with Keycloak!

Just a question though... After I login for the first time, it takes me to a "Complete registration" screen, with my info already filled in, and a Signup button.

Is there a way to skip this screen and auto create the user? Using LDAP, there is a setting called LDAP_AUTOCREATE_USERS that does this, but I didn't find a similar setting for OIDC.

**Comment by brunobastosg** [comment]
I have one more question. I previously used LDAP authentication and now I'm migrating to OIDC.

However, if the LDAP user already exists, the OIDC login says user already exists. Is there any way to "reuse" the same user if it was created by LDAP login?

**Comment by evgenyfadeev** [comment]
If you set `TRUST_EMAIL = True` in the oidc provider module the oidc user will authenticate existing user with matching email, is that doing what you expect?

Here is where this check is done:

https://github.com/ASKBOT/askbot-devel/blob/master/askbot/deps/django_authopenid/protocols/oidc/views.py#L64

**Comment by brunobastosg** [comment]
> If you set `TRUST_EMAIL = True` in the oidc provider module the oidc user will authenticate existing user with matching email, is that doing what you expect?

Thanks. The email field of the LDAP user was empty, that's why it hadn't work before.



> Is there a way to skip this screen and auto create the user? Using LDAP, there is a setting called LDAP_AUTOCREATE_USERS that does this, but I didn't find a similar setting for OIDC.

How about this? Is it possible? If not and you could give me directions on how to implement it, I'd be happy to.

**Comment by evgenyfadeev** [comment]
Sure, I think there is a solution, if you want to implement, please go ahead.

First you need to activate the livesetting "ALLOW_ACCOUNT_RECOVERY_BY_EMAIL", 'Allow account recovery by email'.

When this flag is `True` and if the email is taken upon the registration attempt, under the registration form (along with the "email taken" which is shown currently), render an additional form, posting to this view: https://github.com/ASKBOT/askbot-devel/blob/master/askbot/deps/django_authopenid/views.py#L1434
This additional form is like `authopenid/account_recovery_form.html `, but the email input should be hidden.

Once the user clicks that button and then opens the emailed link, login is done (but the OIDC login is not yet connected, for that - see below)

----

The last piece is to connect the user with the login provider (OIDC) in this case - create a `User Association` db record.

Here is how `UserAssociation` is created https://github.com/ASKBOT/askbot-devel/blob/master/askbot/deps/django_authopenid/views.py#L104

This code should be placed here: https://github.com/ASKBOT/askbot-devel/blob/master/askbot/deps/django_authopenid/views.py#L1481

It should run only if both `user_identifier` and `login_provider_name` are present in the `request.session`
(and use theme to create the `UserAssociation`)

 finally - call function `cleanup_post_register_session(request)` - this will erase the session values used during the registration process.




In that form make the email field hidden input.

Once that form is submitted, user will receive an email with a verification code.

**Comment by brunobastosg** [comment]
No problem. I'll close the issue since I got it working with Keycloak.

For reference if anyone is wondering:

```
BIG_BUTTON = True
ORDER_NUMBER = 1
NAME = 'Keycloak'
ICON_MEDIA_PATH = 'https://www.keycloak.org/resources/images/keycloak_icon_512px.svg'
DISPLAY_NAME = 'Keycloak'
TYPE = 'oidc'
TRUST_EMAIL = True
TOOLTIP_TEXT = 'Sign in via Keycloak'
EXTRA_TOKEN_NAME = 'Keycloak login name and password'
OIDC_AUDIENCE = 'api://default'
OIDC_PROVIDER_URL = 'https://<your keycloak provider domain>/auth/realms/<realm name>'
OIDC_CLIENT_ID = '<your client id>'
OIDC_CLIENT_SECRET = '<your client secret>'
```
